export type Role = 'ADMIN' | 'SALES_MANAGER' | 'SALES_EXECUTIVE'

export const ROLES: Record<Role, Role> = {
  ADMIN: 'ADMIN',
  SALES_MANAGER: 'SALES_MANAGER',
  SALES_EXECUTIVE: 'SALES_EXECUTIVE',
}
